Fix gpg already running error on MacOS
I had commented out starting gpg-agent on teminal session because it
kept giving me an annoying error message. To work around I just manually
called the eval command whenever I needed to use gpg and it would run
for the remainder of my session.

Now I'm checking if gpg-agent is already running and start it if the
/bye argument exit code returns an error. It won't fix all use cases,
but hopefully the more frequent ones.

diff --git a/oh-my-zsh/zshrc b/oh-my-zsh/zshrc
--- a/oh-my-zsh/zshrc
+++ b/oh-my-zsh/zshrc
@@ -48,15 +48,25 @@ if [[ $OSTYPE =~ "darwin" ]]; then
   #alias ls="ls --color=auto --group-directories-first"
   alias mux="tmuxinator"
 
-  # Get gpg-agent to work on osx
-  #eval $(gpg-agent --daemon)
-  export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
+  # This ugly section of code gets GPG and GPG-AGENT to work on MacOS
+  unset SSH_AGENT_PID
+  if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
+    export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
+  fi
   GPG_TTY=$(tty)
   export GPG_TTY
   if [ -f "${HOME}/.gpg-agent-info" ]; then
     . "${HOME}/.gpg-agent-info"
     export GPG_AGENT_INFO
     export SSH_AUTH_SOCK
+  fi
+  # There is no straight forward way to detect if gpg-agent is running. If you try to run 
+  # gpg-agent while it's already running, it displays an annoying error message whenever
+  # a new terminal session is opened. So work around this, I'm piping everything from
+  # gpg-agent to /dev/null to get rid of the message and then check the exit code to
+  # see if it has already been running.
+  if ! gpg-agent /bye > /dev/null 2>&1; then
+    eval $(gpg-agent --daemon)
   fi
 
 elif [[ $OSTYPE == "linux-gnu" ]]; then
